# Generated by Django 2.2 on 2022-06-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0008_player_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTrophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5, verbose_name='Temporada')),
                ('competition', models.CharField(max_length=100, verbose_name='Competição')),
                ('category', models.CharField(max_length=200, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('player_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_trophies', to='players.Player', verbose_name='Vencedor')),
            ],
            options={
                'verbose_name': 'Prêmio Individual',
                'verbose_name_plural': 'Prêmios Individuals',
                'ordering': ['competition'],
            },
        ),
    ]
