# Generated by Django 2.2 on 2022-06-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0008_player_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonIndividualPlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5, verbose_name='Temporada')),
                ('competition', models.CharField(max_length=100, verbose_name='Competição')),
                ('club', models.CharField(max_length=200, verbose_name='Clube')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('player_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_individual_player_stats', to='players.Player', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Statistica Individual Por Temporada',
                'verbose_name_plural': 'Statisticas Individuais Por Temporada',
                'ordering': ['season'],
            },
        ),
    ]
