# Generated by Django 2.2 on 2022-06-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_individual_player_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonindividualplayerstats',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='Assistencias'),
        ),
        migrations.AddField(
            model_name='seasonindividualplayerstats',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Gols'),
        ),
        migrations.AddField(
            model_name='seasonindividualplayerstats',
            name='hard_saves',
            field=models.IntegerField(default=0, verbose_name='Defesas dificeis'),
        ),
        migrations.AddField(
            model_name='seasonindividualplayerstats',
            name='saves',
            field=models.IntegerField(default=0, verbose_name='Defesas'),
        ),
        migrations.AddField(
            model_name='seasonindividualplayerstats',
            name='shots_on_target',
            field=models.IntegerField(default=0, verbose_name='Chutes no alvo'),
        ),
        migrations.AddField(
            model_name='seasonindividualplayerstats',
            name='tackles',
            field=models.IntegerField(default=0, verbose_name='Disputas ganhas'),
        ),
    ]
