# Generated by Django 4.0.5 on 2024-04-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('birth_year', models.CharField(max_length=4)),
                ('preferred_formation', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-2-3-1', '4-2-3-1'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3')], default='4-3-3', max_length=10)),
                ('play_mode', models.TextField(choices=[('Offensive', 'Offensive'), ('Defensive', 'Defensive'), ('Counterattack', 'Counterattack'), ('Addaptive', 'Addaptive')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='app.club', verbose_name='current club')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['name'],
            },
        ),
    ]
