# Generated by Django 4.0.5 on 2024-04-07 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonIndividualPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=4)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('hard_saves', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club', verbose_name='club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_individual_player_stats', to='app.player', verbose_name='player')),
            ],
            options={
                'ordering': ['season'],
            },
        ),
    ]
