# Generated by Django 4.0.5 on 2024-04-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_competitions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitions',
            options={'verbose_name': 'Competition'},
        ),
    ]
