# Generated by Django 2.2 on 2022-06-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_auto_20220615_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5, verbose_name='Temporada')),
                ('competition', models.CharField(max_length=200, verbose_name='Competição')),
                ('points', models.IntegerField(verbose_name='Pontos')),
                ('matches_played', models.IntegerField(verbose_name='Partidas Jogadas')),
                ('won', models.IntegerField(verbose_name='Vitórias')),
                ('draw', models.IntegerField(verbose_name='Empates')),
                ('lost', models.IntegerField(verbose_name='Derrotas')),
                ('goals_for', models.IntegerField(verbose_name='Gols feitos')),
                ('goals_against', models.IntegerField(verbose_name='Gols sofridos')),
                ('goals_diff', models.IntegerField(verbose_name='Saldo de gols')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.Club', verbose_name='Clube')),
            ],
        ),
    ]
