# Generated by Django 2.2 on 2022-05-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20220513_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='current_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='clubs.Club', verbose_name='Clube Atual'),
        ),
    ]
