# Generated by Django 2.2 on 2022-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_auto_20220514_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='salary',
            field=models.FloatField(default='5_000.00', verbose_name='Salário'),
        ),
    ]
