# Generated by Django 2.2 on 2022-05-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5, verbose_name='Temporada')),
                ('competition', models.CharField(max_length=100, verbose_name='Competição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('club_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_owner', to='clubs.Club', verbose_name='Clube Campeão')),
            ],
            options={
                'verbose_name': 'Troféu',
                'verbose_name_plural': 'Troféus',
                'ordering': ['competition'],
            },
        ),
    ]
