# Generated by Django 2.2 on 2022-06-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='club_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='clubs.Club', verbose_name='Clube Campeão'),
        ),
    ]
