# Generated by Django 2.2 on 2022-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='salary_budget',
            field=models.FloatField(default=500000, verbose_name='Verba de salário'),
        ),
        migrations.AddField(
            model_name='club',
            name='total_budget',
            field=models.FloatField(default=2000000, verbose_name='Verba Total'),
        ),
    ]
