# Generated by Django 4.0.5 on 2022-07-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220615_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome'),
        ),
    ]
