# Generated by Django 2.2 on 2022-04-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0004_auto_20220424_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=200, verbose_name='Competição')),
                ('season', models.CharField(max_length=5, verbose_name='Temporada')),
                ('hour', models.CharField(max_length=5, verbose_name='Horario')),
                ('score', models.CharField(max_length=10, verbose_name='Placar')),
                ('stadium', models.TextField(verbose_name='Estádio')),
                ('home_shots', models.IntegerField(verbose_name='Chutes do Anfitrião')),
                ('home_shots_on_target', models.IntegerField(verbose_name='Chutes no Alvo Anfitrião')),
                ('home_fouls', models.IntegerField(verbose_name='Faltas do Anfitrião')),
                ('home_tackles', models.IntegerField(verbose_name='Divididas do Anfitrião')),
                ('home_saves', models.IntegerField(verbose_name='Defesas do Anfitrião')),
                ('home_ball_possession', models.IntegerField(verbose_name='Posse de Bola do Anfitrião')),
                ('home_offsides', models.IntegerField(verbose_name='Impedimentos do Anfitrião')),
                ('home_freekicks', models.IntegerField(verbose_name='Faltas do Anfitrião')),
                ('away_shots', models.IntegerField(verbose_name='Chutes do Visitante')),
                ('away_shots_on_target', models.IntegerField(verbose_name='Chutes no Alvo do Visitante')),
                ('away_fouls', models.IntegerField(verbose_name='Faltas do Visitante')),
                ('away_tackles', models.IntegerField(verbose_name='Divididas do Visitante')),
                ('away_saves', models.IntegerField(verbose_name='Defesas do Visitante')),
                ('away_ball_possession', models.IntegerField(verbose_name='Posse de bola do Visitante')),
                ('away_offsides', models.IntegerField(verbose_name='Impedimentos do Visitante')),
                ('away_freekicks', models.IntegerField(verbose_name='Faltas do Visitante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_away', to='players.Club', verbose_name='Time Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_home', to='players.Club', verbose_name='Time Anfitrião')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['season', 'competition'],
            },
        ),
    ]
