# Generated by Django 4.0.5 on 2022-07-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_name'),
        ('games', '0002_auto_20220424_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_away', to='clubs.club', verbose_name='Time Visitante'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_home', to='clubs.club', verbose_name='Time Anfitrião'),
        ),
    ]
