# Generated by Django 2.2 on 2022-04-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('nationality', models.CharField(max_length=150, verbose_name='Nacionalidade')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('overall', models.IntegerField(verbose_name='Média')),
                ('position', models.CharField(max_length=30, verbose_name='Posição')),
                ('matches', models.IntegerField(default=0, verbose_name='Partidas')),
                ('goals', models.IntegerField(default=0, verbose_name='Gols')),
                ('assists', models.IntegerField(default=0, verbose_name='Assistencias')),
                ('teste', models.IntegerField(default=0, verbose_name='teste')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['overall', 'name'],
            },
        ),
    ]
