# Generated by Django 2.2 on 2022-04-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('country', models.CharField(max_length=200, verbose_name='País')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='Estado')),
                ('coeff', models.IntegerField(verbose_name='Coeficiente')),
                ('formation', models.CharField(max_length=10, verbose_name='Formação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
                'ordering': ['coeff', 'name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='players.Club'),
            preserve_default=False,
        ),
    ]
