# Generated by Django 2.2 on 2022-04-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20220424_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='players.Club', verbose_name='Clube Atual'),
        ),
    ]
