# Generated by Django 2.2 on 2022-04-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20220424_0910'),
        ('players', '0004_auto_20220424_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', verbose_name='Clube Atual'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
