# Generated by Django 2.2 on 2022-05-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20220424_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.Club', verbose_name='Clube Atual'),
        ),
    ]
